connectionTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: nod-connections-prod-v2
    attributeDefinitions:
      - AttributeName: connectionID
        AttributeType: S
      - AttributeName: meetingID
        AttributeType: S
    keySchema:
      - AttributeName: connectionID
        KeyType: HASH
      - AttributeName: meetingID
        KeyType: RANGE
    globalSecondaryIndexes:
      - IndexName: meetingIndex
        KeySchema:
          - AttributeName: meetingID
            KeyType: HASH
          - AttributeName: connectionID
            KeyType: RANGE
        Projection:
          ProjectionType: "KEYS_ONLY"
    region: us-east-1

teamsTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: nod-teams-prod-v2
    attributeDefinitions:
      - AttributeName: teamName
        AttributeType: S
    keySchema:
      - AttributeName: teamName
        KeyType: HASH
    region: us-east-1

websocketApi:
  component: "@serverless/backend-socket"
  inputs:
    name: nod-prod-websocket-v2
    stage: prod
    description: Nod-Prod Websocket Backend v2
    region: us-east-1
    memory: 128
    timeout: 10
    env:
      connectionDb: ${connectionTable.name}
      teamsDb: ${teamsTable.name}
    code:
      src: ../../backend/socket
